@php namespace App\Entities;

use CodeIgniter\Entity;

/**
 * {! name !} Entity
 *
 * Generated by Vulcan at {! today !}
 */
class {! name !} extends Entity
{
{! propertyList !}

	protected $_options = [
        'datamap' => [],
        'dates' => ['created_at', 'updated_at'],
        'casts'   => [{! casts !}],
    ];
}
