@php namespace App\Entities;

use CodeIgniter\Entity;

/**
 * {! name !} Entity
 *
{! docProperties !}
 *
 * Generated by Vulcan at {! today !}
 */
class {! name !} extends Entity
{
{! propertyList !}

	protected $_options = [
        'datamap' => [],
        'casts'   => [{! casts !}],
    ];
}
