@php namespace App\Entities;

use CodeIgniter\Entity;

/**
 * {! name !} Entity
 *
 * Generated by Vulcan at {! today !}
 */
class {! name !} extends Entity
{
    protected $datamap = [];

    protected $dates = ['created_at', 'updated_at'];

    protected $casts = [{! casts !}];
}
