@php namespace {namespace}\Commands;

use CodeIgniter\CLI\CLI;
use CodeIgniter\CLI\BaseCommand;

/**
 * {! name !} Command
 *
 * Generated by Vulcan at {! today !}
 */
class {name} extends BaseCommand
{
    /**
     * A heading this command is grouped under
     * when listed via `php spark`
     */
    protected $group = '';

    /**
     * The Command's name
     *
     * @var string
     */
    protected $name = '';

    /**
     * The Command's short description
     *
     * @var string
     */
    protected $description = '';

    /**
     * The main entry point into the command.
     * All base logic should happen here.
     */
    public function run(array $params=[])
    {
        //
    }
}
