@php namespace {namespace}\Controllers;

use CodeIgniter\Controller;

/**
 * {! name !} Controller
 *
 * Generated by Vulcan at {! today !}
 */
class {name} extends Controller
{
    public function index()
    {
        //
    }
}
