@php namespace {namespace}\Models;

use CodeIgniter\Model;

/**
 * {! name !} Model
 *
 * Generated by Vulcan at {! today !}
 */
class {! name !} extends Model
{
    protected $table      = '{! table !}';
    protected $primaryKey = '{! primaryKey !}';

    protected $returnType = '{! returnType !}';
    protected $useSoftDeletes = {! useSoftDeletes !};

    protected $allowedFields = [{! allowedFields !}];

    protected $useTimestamps = {! useTimestamps !};
    protected $createdField  = '{! createdField !}';
    protected $updatedField  = '{! updatedField !}';
    protected $dateFormat    = '{! dateFormat !}';

    protected $validationRules    = {! validationRules !};
    protected $validationMessages = [];
    protected $skipValidation     = false;
}
